services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - dostnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    env_file: ./frontend/.env  
    ports:
      - "4173:4173"
    networks:
      - dostnet
    depends_on:
      - backend

networks:
  dostnet:
    driver: bridge