services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      postgresdocument:
        condition: service_healthy
    networks:
      - dostnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    env_file: ./frontend/.env  
    ports:
      - "4173:4173"
    networks:
      - dostnet
    depends_on:
      - backend

  postgresdocument:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: dbDocumentLogbook
      POSTGRES_USER: dostone
      POSTGRES_PASSWORD: dostonepass
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dostone -d dbDocumentLogbook"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dostnet
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  dostnet:
    driver: bridge

volumes:
  pgdata:
